FROM python:3.11-slim

WORKDIR /usr/app

RUN pip install --no-cache-dir \
    dlt[postgres,clickhouse,sql_database,parquet] \
    clickhouse-connect \
    polars xgboost scikit-learn pyarrow shap mlflow \
    confluent-kafka redis pandas streamlit plotly \
    psycopg2-binary duckdb

CMD ["/bin/sh"]
