apiVersion: 1
datasources:
  - name: ClickHouse
    uid: clickhouse-riskfabric
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      username: riskfabric_user
      defaultDatabase: riskfabric
    secureJsonData:
      password: "123"
    editable: true
