# Generated by Django 4.2.30 on 2026-07-01 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Reference to the transaction ID from the pipeline', max_length=255, unique=True)),
                ('score', models.FloatField(help_text='Fraud probability score from the model')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('investigating', 'Investigating'), ('confirmed_fraud', 'Confirmed Fraud'), ('cleared', 'Cleared'), ('false_positive', 'False Positive')], default='pending', help_text='Current review status of the case', max_length=50)),
                ('flagged_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the transaction was flagged')),
                ('reviewed_by', models.CharField(blank=True, help_text='Analyst identifier who reviewed the case', max_length=255, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when the review was completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Free-text analyst investigation notes', null=True)),
                ('flag_reasons', models.JSONField(blank=True, help_text='SHAP top features or rule triggers that flagged this transaction', null=True)),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-flagged_at'],
            },
        ),
    ]
